services:
  web:
    build: "./TrackThat-Front-End"
    ports:
      - 5173:5173
    volumes:
      - ./TrackThat-Front-End:/app
      - /app/node_modules  # Exclude node_modules from being overwritten
    command: ["npm", "run", "dev"]

  api:
    build: "./TrackThat-Back-End"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - ./TrackThat-Back-End:/app